### PR TITLE
ENH: MacOS torch requirements

### LINKED ISSUE #29: installing on macosx
Does not seem to work with python3.8. Breaks at the zipp install. 
ERROR: Ignored the following versions that require a different python version: 8.13.1 Requires-Python >=3.9; 8.13.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cu111 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.9.1+cu111

If I create another virtualenv with python3.10, it also breaks on zipp install and then tells me I need python < 3.9...

Don't know what to do with this but ideally, we would have a version of the code compatible with python3.10 like scilpy. Maybe Arnaud or Francois have some insights...

### PR DESCRIPTION
**Pull request by AntoineTheb**
Add platform-specific torch requirements. I will need someone with a computer running MacOS to test it.

Fixes #29 .

### CODE REVIEW

**Comment by mdesco** [comment]
FYI, when I run pip install -r requirements.txt I get the following warning:
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Ignoring torch: markers 'sys_platform != "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform != "darwin"' don't match your environment

Otherwise, everything installs well. I will now test.

**Comment by AntoineTheb** [comment]
@mdesco Cool ! That means my fix works ! pip ignores some packages based on the distribution (CUDA stuff on OSX, for example).

**Comment by mdesco** [comment]
pip install git+https://github.com/scilus/scilpy@1.3.0#egg=scilpy

This line crashes on sklearn on my end. 

Collecting sklearn (from nilearn==0.6.*->scilpy)
  Using cached sklearn-0.0.post5.tar.gz (3.7 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by AntoineTheb** [comment]
Ahhh yes, that’s an issue with the version 1.3 of scilpy (would it be possible to fix it ?) . Fortunately, we can bypass the error with a flag as mentioned in the error message. I’ll add it to the  README !

**Comment by mdesco** [comment]
Ok merge it to master and then I can test on my mac

**Pull request closed without merging**
